/*
  Catalogo de las fotos y videos fijos del sitio, para la seccion "Imagenes
  del sitio" del panel. GENERADO por dev/catalogo-imagenes.cjs a partir de
  las rutas de src/data: si se anade una foto nueva a los datos, hay que
  volver a generarlo (npm run catalogo) para que aparezca en el panel.
*/

export interface ImagenCatalogo {
  /** Ruta original en el codigo; es la clave de la sustitucion. */
  ruta: string;
  grupo: string;
  /** Donde esta: la pagina, el producto o la seccion. */
  contexto: string;
  /** Que se ve en ella. */
  descripcion: string;
  esVideo: boolean;
}

export const CATALOGO_IMAGENES: ImagenCatalogo[] = [
  { ruta: '/img/logos/linkxpace.png', grupo: 'Inicio y menú', contexto: 'LinkXpace', descripcion: 'Logotipo de LinkXpace', esVideo: false },
  { ruta: '/img/logos/siegix-crm.png', grupo: 'Inicio y menú', contexto: 'SIEGIX CRM', descripcion: 'Logotipo de SIEGIX CRM', esVideo: false },
  { ruta: '/img/logos/siegix-provider.png', grupo: 'Inicio y menú', contexto: 'SIEGIX Provider', descripcion: 'Logotipo de SIEGIX Provider', esVideo: false },
  { ruta: '/img/logos/radiologox.png', grupo: 'Inicio y menú', contexto: 'RadiologoX', descripcion: 'Logotipo de RadiologoX', esVideo: false },
  { ruta: '/img/logos/ecoturnox.png', grupo: 'Inicio y menú', contexto: 'ECOTurnox', descripcion: 'Logotipo de ECOTurnox', esVideo: false },
  { ruta: '/img/logos/siegix-health.png', grupo: 'Inicio y menú', contexto: 'SIEGIX Health', descripcion: 'Logotipo de SIEGIX Health', esVideo: false },
  { ruta: '/img/logos/linkrix.png', grupo: 'Inicio y menú', contexto: 'LINKRix', descripcion: 'Logotipo de LINKRix', esVideo: false },
  { ruta: '/img/logos/linkburnprint.png', grupo: 'Inicio y menú', contexto: 'LinkBurnPrint', descripcion: 'Logotipo de LinkBurnPrint', esVideo: false },
  { ruta: '/img/logos/consultoriox.png', grupo: 'Inicio y menú', contexto: 'ConsultorioX', descripcion: 'Logotipo de ConsultorioX', esVideo: false },
  { ruta: '/img/menu/sector-publico.webp', grupo: 'Inicio y menú', contexto: 'Sector Público', descripcion: 'Personal sanitario en un hospital público', esVideo: false },
  { ruta: '/img/menu/sector-privado.webp', grupo: 'Inicio y menú', contexto: 'Sector Privado', descripcion: 'Recepción de una clínica privada', esVideo: false },
  { ruta: '/img/menu/internacional.webp', grupo: 'Inicio y menú', contexto: 'Internacional', descripcion: 'Conexiones internacionales sobre un mapa del mundo', esVideo: false },
  { ruta: '/img/recursos/conferencias.webp', grupo: 'Inicio y menú', contexto: 'Conferencias', descripcion: 'Ponencia de LINKDICOM ante el público de un congreso', esVideo: false },
  { ruta: '/img/recursos/webinars.webp', grupo: 'Inicio y menú', contexto: 'Webinars', descripcion: 'Webinar de LINKDICOM en la pantalla de un portátil', esVideo: false },
  { ruta: '/img/recursos/entrevistas.webp', grupo: 'Inicio y menú', contexto: 'Entrevistas', descripcion: 'Micrófono de estudio preparado para una entrevista', esVideo: false },
  { ruta: '/img/recursos/materiales.webp', grupo: 'Inicio y menú', contexto: 'Materiales de Apoyo', descripcion: 'Manual de usuario PACS-RIS de LINKDICOM', esVideo: false },
  { ruta: '/img/menu/acerca-de-nosotros.webp', grupo: 'Inicio y menú', contexto: 'Quiénes somos', descripcion: 'Sede de LINKDICOM iluminada al anochecer', esVideo: false },
  { ruta: '/img/menu/obra-social.webp', grupo: 'Inicio y menú', contexto: 'Obra social', descripcion: 'Manos sosteniendo un corazón', esVideo: false },
  { ruta: '/img/menu/nuestros-valores.webp', grupo: 'Inicio y menú', contexto: 'Nuestros valores', descripcion: 'Manos de un equipo unidas en señal de compromiso', esVideo: false },
  { ruta: '/img/menu/trabaja-con-nosotros.webp', grupo: 'Inicio y menú', contexto: 'Trabaja con nosotros', descripcion: 'Puesto de trabajo en la oficina de LINKDICOM', esVideo: false },
  { ruta: '/img/menu/politicas-y-terminos.webp', grupo: 'Inicio y menú', contexto: 'Políticas y términos', descripcion: 'Documento impreso sobre una mesa', esVideo: false },
  { ruta: '/img/menu/contacto.webp', grupo: 'Inicio y menú', contexto: 'Contáctanos', descripcion: 'Escritorio de atención de LINKDICOM', esVideo: false },
  { ruta: '/img/ecosistemas/centros-de-diagnostico-tarjeta.webp', grupo: 'Inicio y menú', contexto: 'Centros de Diagnóstico', descripcion: 'Recepción de un centro de diagnóstico con el equipo de imagen al fondo', esVideo: false },
  { ruta: '/img/ecosistemas/hospitalario-tarjeta.webp', grupo: 'Inicio y menú', contexto: 'Hospitales', descripcion: 'Entrada de un hospital con la pantalla de turnos en la sala de espera', esVideo: false },
  { ruta: '/img/ecosistemas/laboratorios-tarjeta.webp', grupo: 'Inicio y menú', contexto: 'Laboratorios', descripcion: 'Técnica de laboratorio procesando muestras junto a la pantalla de LaboratoriuX', esVideo: false },
  { ruta: '/img/ecosistemas/consultorios-tarjeta.webp', grupo: 'Inicio y menú', contexto: 'Consultorios y Redes Médicas', descripcion: 'Médico revisando el historial de una paciente en la tableta', esVideo: false },
  { ruta: '/img/productos/radiologox/hero.webp', grupo: 'Productos', contexto: 'Plataforma completa de imágenes diagnósticas y teleradiología', descripcion: 'Radiólogo revisando estudios en varias pantallas', esVideo: false },
  { ruta: '/img/productos/radiologox/panel.webp', grupo: 'Productos', contexto: 'Plataforma completa de imágenes diagnósticas y teleradiología', descripcion: 'Estación de trabajo de RadiologoX mostrando estudios de imagen', esVideo: false },
  { ruta: '/img/productos/radiologox/descripcion.webp', grupo: 'Productos', contexto: 'Todo tu flujo radiológico en una sola plataforma', descripcion: 'Especialista interpretando un estudio en RadiologoX', esVideo: false },
  { ruta: '/img/productos/radiologox/beneficios.webp', grupo: 'Productos', contexto: 'Menos tiempo de espera, más capacidad de diagnóstico', descripcion: 'Equipo médico revisando indicadores de productividad', esVideo: false },
  { ruta: '/img/productos/radiologox/funcionalidades.webp', grupo: 'Productos', contexto: 'Herramientas pensadas para el trabajo diario', descripcion: 'Visor diagnóstico de RadiologoX con herramientas de medición', esVideo: false },
  { ruta: '/img/productos/radiologox/integraciones.webp', grupo: 'Productos', contexto: 'Conecta con lo que ya tienes', descripcion: 'Diagrama de integración entre sistemas hospitalarios', esVideo: false },
  { ruta: '/img/productos/ecoturnox/hero.webp', grupo: 'Productos', contexto: 'Sistema inteligente de gestión de turnos y filas', descripcion: 'Sala de espera con pantallas de llamado y kiosco de turnos ECOTurnox', esVideo: false },
  { ruta: '/img/productos/ecoturnox/panel.webp', grupo: 'Productos', contexto: 'Sistema inteligente de gestión de turnos y filas', descripcion: 'Kiosco de autoservicio de ECOTurnox junto a la pantalla de llamado', esVideo: false },
  { ruta: '/img/productos/ecoturnox/descripcion.webp', grupo: 'Productos', contexto: 'Una experiencia de espera más organizada y eficiente', descripcion: 'Pantalla de llamado de turnos en una sala de espera', esVideo: false },
  { ruta: '/img/productos/ecoturnox/beneficios.webp', grupo: 'Productos', contexto: 'Una sala de espera que deja de ser un problema', descripcion: 'Personal de recepción atendiendo con el sistema de turnos', esVideo: false },
  { ruta: '/img/productos/ecoturnox/funcionalidades.webp', grupo: 'Productos', contexto: 'Del turno a la cita, todo en un mismo flujo', descripcion: 'Paciente sacando su turno en el kiosco de autoservicio', esVideo: false },
  { ruta: '/img/productos/ecoturnox/integraciones.webp', grupo: 'Productos', contexto: 'Conectado con el resto de tu operación', descripcion: 'Esquema de integración entre turnos, historia clínica y facturación', esVideo: false },
  { ruta: '/img/productos/siegix-health/hero.webp', grupo: 'Productos', contexto: 'Control total para una gestión hospitalaria más eficiente', descripcion: 'Panel financiero de SIEGIX Health en dos monitores', esVideo: false },
  { ruta: '/img/productos/siegix-health/panel.webp', grupo: 'Productos', contexto: 'Control total para una gestión hospitalaria más eficiente', descripcion: 'Cuadro de mando de SIEGIX Health con indicadores de facturación', esVideo: false },
  { ruta: '/img/productos/siegix-health/descripcion.webp', grupo: 'Productos', contexto: 'Una plataforma completa para la gestión financiera y administrativa', descripcion: 'Contabilidad y facturación electrónica en SIEGIX Health', esVideo: false },
  { ruta: '/img/productos/siegix-health/beneficios.webp', grupo: 'Productos', contexto: 'Cierra el mes sin pelearte con los números', descripcion: 'Responsable financiero revisando el cierre del mes', esVideo: false },
  { ruta: '/img/productos/siegix-health/funcionalidades.webp', grupo: 'Productos', contexto: 'Todo el back office de tu institución', descripcion: 'Módulos administrativos de SIEGIX Health', esVideo: false },
  { ruta: '/img/productos/siegix-health/integraciones.webp', grupo: 'Productos', contexto: 'Habla con el resto de tus sistemas', descripcion: 'Diagrama de integración de la facturación con otros sistemas', esVideo: false },
  { ruta: '/img/productos/linkrix/hero.webp', grupo: 'Productos', contexto: 'El puente entre tus equipos y tu información radiológica', descripcion: 'Estación de radiología con la worklist de LINKRix en pantalla', esVideo: false },
  { ruta: '/img/productos/linkrix/panel.webp', grupo: 'Productos', contexto: 'El puente entre tus equipos y tu información radiológica', descripcion: 'Lista de trabajo de LINKRix junto al equipo LINKConnect', esVideo: false },
  { ruta: '/img/productos/linkrix/descripcion.webp', grupo: 'Productos', contexto: 'Optimiza el flujo radiológico de tu institución', descripcion: 'Técnico gestionando la lista de trabajo radiológica', esVideo: false },
  { ruta: '/img/productos/linkrix/beneficios.webp', grupo: 'Productos', contexto: 'El equipo deja de esperar y el paciente también', descripcion: 'Sala de adquisición con el estudio ya identificado', esVideo: false },
  { ruta: '/img/productos/linkrix/funcionalidades.webp', grupo: 'Productos', contexto: 'Control de la sala, no solo de la imagen', descripcion: 'Panel de gestión de equipos y salas de LINKRix', esVideo: false },
  { ruta: '/img/productos/linkrix/integraciones.webp', grupo: 'Productos', contexto: 'El nexo entre modalidades y sistemas', descripcion: 'Dispositivo LINKConnect conectando equipos de imagen', esVideo: false },
  { ruta: '/img/ecosistemas/laboratorios.webp', grupo: 'Productos', contexto: 'Gestión de laboratorio clínico', descripcion: 'Panel de muestras de LaboratoriuX sobre un laboratorio clínico', esVideo: false },
  { ruta: '/img/productos/linkburnprint/hero.webp', grupo: 'Productos', contexto: 'Resultados físicos y digitales de forma simple y profesional', descripcion: 'Disco con etiqueta impresa y código QR junto a la grabadora', esVideo: false },
  { ruta: '/img/productos/linkburnprint/panel.webp', grupo: 'Productos', contexto: 'Resultados físicos y digitales de forma simple y profesional', descripcion: 'Grabadora e impresora de LinkBurnPrint con estudios en lámina', esVideo: false },
  { ruta: '/img/productos/linkburnprint/descripcion.webp', grupo: 'Productos', contexto: 'Una solución completa para la entrega de estudios', descripcion: 'Etiqueta con código QR impresa sobre el disco del estudio', esVideo: false },
  { ruta: '/img/productos/linkburnprint/beneficios.webp', grupo: 'Productos', contexto: 'Una entrega que se ve profesional y queda registrada', descripcion: 'Paciente recibiendo su estudio en recepción', esVideo: false },
  { ruta: '/img/productos/linkburnprint/funcionalidades.webp', grupo: 'Productos', contexto: 'Etiqueta, graba, imprime y registra', descripcion: 'Puesto de trabajo de entrega de resultados', esVideo: false },
  { ruta: '/img/productos/linkburnprint/integraciones.webp', grupo: 'Productos', contexto: 'Toma los estudios directamente del PACS', descripcion: 'Esquema de integración con el PACS de la institución', esVideo: false },
  { ruta: '/img/productos/consultoriox/hero.webp', grupo: 'Productos', contexto: 'La plataforma inteligente para gestionar tu consultorio y tus pacientes', descripcion: 'Médico atendiendo a una paciente en su consultorio con la tableta en la mano', esVideo: false },
  { ruta: '/img/productos/consultoriox/panel.webp', grupo: 'Productos', contexto: 'La plataforma inteligente para gestionar tu consultorio y tus pacientes', descripcion: 'Panel de ConsultorioX con la agenda del día y el paciente en consulta', esVideo: false },
  { ruta: '/img/productos/consultoriox/descripcion.webp', grupo: 'Productos', contexto: 'Todo tu consultorio en una sola plataforma', descripcion: 'Panel de ConsultorioX abierto en la consulta del médico', esVideo: false },
  { ruta: '/img/productos/consultoriox/beneficios.webp', grupo: 'Productos', contexto: 'Menos ausencias y pacientes mejor informados', descripcion: 'Paciente consultando en el móvil la confirmación de su cita', esVideo: false },
  { ruta: '/img/productos/consultoriox/funcionalidades.webp', grupo: 'Productos', contexto: 'Del calendario a la receta, sin cambiar de programa', descripcion: 'Calendario, historial clínico y recetas digitales de ConsultorioX', esVideo: false },
  { ruta: '/img/productos/consultoriox/integraciones.webp', grupo: 'Productos', contexto: 'Conectado con lo que ya usas', descripcion: 'Esquema de integración de ConsultorioX con facturación, ERP, CRM y RIS', esVideo: false },
  { ruta: '/img/ecosistemas/centros-de-diagnostico.webp', grupo: 'Ecosistemas', contexto: 'Centros de Diagnóstico', descripcion: 'Sala de un centro de diagnóstico con equipos y personal técnico', esVideo: false },
  { ruta: '/img/ecosistemas/hospitalario.webp', grupo: 'Ecosistemas', contexto: 'Hospitalario', descripcion: 'Entrada de un hospital moderno con la sala de espera y el panel de turnos', esVideo: false },
  { ruta: '/img/ecosistemas/consultorios.webp', grupo: 'Ecosistemas', contexto: 'La gestión de tu consultorio,', descripcion: 'Médico atendiendo a una paciente con ConsultorioX en pantalla', esVideo: false },
  { ruta: '/img/sectores/hero-publico.webp', grupo: 'Sectores', contexto: 'Sector Público', descripcion: 'Instalaciones de salud pública de la República Dominicana', esVideo: false },
  { ruta: '/img/sectores/pacs-isl1.webp', grupo: 'Sectores', contexto: 'Primer Sistema PACS Dominicano (ISL/1)', descripcion: 'Portátil mostrando el panel de ISL/1, evolucionado a SGMM', esVideo: false },
  { ruta: '/img/sectores/rd-hospital.webp', grupo: 'Sectores', contexto: 'RD-Hospital', descripcion: 'Mapa de la República Dominicana con los hospitales de RD-Hospital conectados', esVideo: false },
  { ruta: '/img/sectores/portal-soporte.webp', grupo: 'Sectores', contexto: 'Primer portal de soporte técnico del sector biomédico', descripcion: 'Portal de soporte técnico de LINKDICOM abierto en un portátil', esVideo: false },
  { ruta: '/img/sectores/entrega-en-linea.webp', grupo: 'Sectores', contexto: 'Entrega de imágenes y reportes en línea', descripcion: 'Paciente consultando su radiografía desde el móvil', esVideo: false },
  { ruta: '/img/sectores/robots-cd.webp', grupo: 'Sectores', contexto: 'Primeros en Robots CD', descripcion: 'Impresora robot grabando un CD con la etiqueta de la institución', esVideo: false },
  { ruta: '/img/sectores/administracion-consultorios.webp', grupo: 'Sectores', contexto: 'Administración de Consultorios', descripcion: 'Pantalla de ConsultorioX con la agenda del día', esVideo: false },
  { ruta: '/img/sectores/soluciones-dicom.webp', grupo: 'Sectores', contexto: 'Soluciones DICOM en Dominicana', descripcion: 'Desarrollo de soluciones DICOM sobre estudios de resonancia', esVideo: false },
  { ruta: '/img/sectores/hero-privado.webp', grupo: 'Sectores', contexto: 'Sector Privado', descripcion: 'Equipo de una clínica privada atendiendo en recepción', esVideo: false },
  { ruta: '/img/sectores/venta-equipos.webp', grupo: 'Sectores', contexto: 'Equipos e infraestructura', descripcion: 'Equipo de rayos X instalado en un centro privado', esVideo: false },
  { ruta: '/img/sectores/innovacion-continua.webp', grupo: 'Sectores', contexto: 'Innovación continua', descripcion: 'Especialista trabajando con las soluciones más recientes', esVideo: false },
  { ruta: '/img/sectores/farmacias.webp', grupo: 'Sectores', contexto: 'Farmacias', descripcion: 'Farmacéutica atendiendo en el mostrador', esVideo: false },
  { ruta: '/img/sectores/funerarias.webp', grupo: 'Sectores', contexto: 'Funerarias', descripcion: 'Sala de velatorio preparada', esVideo: false },
  { ruta: '/img/sectores/abogados.webp', grupo: 'Sectores', contexto: 'Buffetes de Abogados', descripcion: 'Despacho de abogados durante una consulta', esVideo: false },
  { ruta: '/img/sectores/bienes-raices.webp', grupo: 'Sectores', contexto: 'Bienes Raíces', descripcion: 'Agente inmobiliario mostrando una propiedad', esVideo: false },
  { ruta: '/img/sectores/otros-sectores.webp', grupo: 'Sectores', contexto: 'Otros Sectores', descripcion: 'Reunión de trabajo en una sala de juntas', esVideo: false },
  { ruta: '/img/sectores/cierre-privado.webp', grupo: 'Sectores', contexto: 'Un socio local que entiende tu realidad', descripcion: 'Reunión de trabajo sobre un proyecto tecnológico', esVideo: false },
  { ruta: '/img/sectores/hero-internacional.webp', grupo: 'Sectores', contexto: 'Internacional', descripcion: 'Red de conexiones sobre el globo terráqueo', esVideo: false },
  { ruta: '/img/internacional/isl1.png', grupo: 'Sectores', contexto: 'Evolución, colaboración y aporte al', descripcion: 'Logotipo del sistema ISL/1', esVideo: false },
  { ruta: '/img/internacional/dcm4che.png', grupo: 'Sectores', contexto: 'Primer sistema PACS dominicano', descripcion: 'Logotipo de dcm4che', esVideo: false },
  { ruta: '/img/internacional/oviyam.png', grupo: 'Sectores', contexto: 'Integración y traducción', descripcion: 'Logotipo de Oviyam', esVideo: false },
  { ruta: '/img/internacional/orthanc.png', grupo: 'Sectores', contexto: 'Primer acercamiento (visor oficial del ISL/1)', descripcion: 'Logotipo de Orthanc', esVideo: false },
  { ruta: '/img/internacional/radiologox.png', grupo: 'Sectores', contexto: 'Mayores contribuciones', descripcion: 'Logotipo de RadiologoX PACS/RIS', esVideo: false },
  { ruta: '/img/internacional/isl1-codigo.webp', grupo: 'Sectores', contexto: 'ISL/1', descripcion: 'Código fuente del ISL/1', esVideo: false },
  { ruta: '/img/internacional/dcm4che-archivo.webp', grupo: 'Sectores', contexto: 'dcm4che', descripcion: 'Consola de archivo DICOM de DCM4CHEE', esVideo: false },
  { ruta: '/img/internacional/oviyam-visor.webp', grupo: 'Sectores', contexto: 'Oviyam', descripcion: 'Visor Oviyam mostrando un estudio de tomografía', esVideo: false },
  { ruta: '/img/internacional/orthanc-servidor.webp', grupo: 'Sectores', contexto: 'Orthanc', descripcion: 'Panel de Orthanc con las etiquetas DICOM de un estudio', esVideo: false },
  { ruta: '/img/internacional/raster.png', grupo: 'Sectores', contexto: 'Gracias por ser parte del camino', descripcion: 'Logotipo de Raster Images', esVideo: false },
  { ruta: '/img/sectores/cierre-internacional.webp', grupo: 'Sectores', contexto: 'Orthanc', descripcion: 'Ala de un avión sobre una ciudad costera al amanecer', esVideo: false },
  { ruta: '/img/empresariales/linkxpace/panel.webp', grupo: 'Soluciones empresariales', contexto: 'Tu presencia digital comienza aquí', descripcion: 'Sitio web de LinkXpace en ordenador y móvil', esVideo: false },
  { ruta: '/img/empresariales/linkxpace/descripcion.webp', grupo: 'Soluciones empresariales', contexto: 'Todo lo que necesitas para llevar tu negocio al siguiente nivel', descripcion: 'Centro de datos con infraestructura en la nube', esVideo: false },
  { ruta: '/img/empresariales/linkxpace/caracteristicas.webp', grupo: 'Soluciones empresariales', contexto: 'Infraestructura pensada para no darte trabajo', descripcion: 'Panel de administración de servicios de LinkXpace', esVideo: false },
  { ruta: '/img/empresariales/linkxpace/planes.webp', grupo: 'Soluciones empresariales', contexto: 'Un plan para cada etapa de tu negocio', descripcion: 'Comparativa de planes de LinkXpace', esVideo: false },
  { ruta: '/img/empresariales/linkxpace/faq.webp', grupo: 'Soluciones empresariales', contexto: 'Dudas habituales antes de contratar', descripcion: 'Asistente virtual de LINKDICOM resolviendo preguntas frecuentes', esVideo: false },
  { ruta: '/img/empresariales/siegix-crm/panel.webp', grupo: 'Soluciones empresariales', contexto: 'Convierte oportunidades en crecimiento', descripcion: 'Panel de SIEGIX CRM con oportunidades y ventas del mes', esVideo: false },
  { ruta: '/img/empresariales/siegix-crm/descripcion.webp', grupo: 'Soluciones empresariales', contexto: 'Todo tu negocio conectado con tus clientes', descripcion: 'Equipo comercial trabajando con SIEGIX CRM', esVideo: false },
  { ruta: '/img/empresariales/siegix-crm/funcionalidades.webp', grupo: 'Soluciones empresariales', contexto: 'Del primer contacto al cliente fiel', descripcion: 'Embudo de ventas en SIEGIX CRM', esVideo: false },
  { ruta: '/img/empresariales/siegix-crm/beneficios.webp', grupo: 'Soluciones empresariales', contexto: 'Nada se pierde entre correos y hojas de cálculo', descripcion: 'Panel de indicadores comerciales', esVideo: false },
  { ruta: '/img/empresariales/siegix-crm/integraciones.webp', grupo: 'Soluciones empresariales', contexto: 'Conectado con el resto de tus herramientas', descripcion: 'Esquema de integraciones de SIEGIX CRM', esVideo: false },
  { ruta: '/img/empresariales/siegix-crm/faq.webp', grupo: 'Soluciones empresariales', contexto: 'Lo que más nos preguntan', descripcion: 'Asistente virtual de LINKDICOM resolviendo preguntas frecuentes', esVideo: false },
  { ruta: '/img/empresariales/siegix-provider/panel.webp', grupo: 'Soluciones empresariales', contexto: 'La plataforma completa para empresas de servicios', descripcion: 'Panel de SIEGIX Provider con servicios y facturación', esVideo: false },
  { ruta: '/img/empresariales/siegix-provider/descripcion.webp', grupo: 'Soluciones empresariales', contexto: 'Gestiona hoy una empresa más eficiente', descripcion: 'SIEGIX Provider en ordenador y móvil sobre un escritorio', esVideo: false },
  { ruta: '/img/empresariales/siegix-provider/funcionalidades.webp', grupo: 'Soluciones empresariales', contexto: 'De la orden de trabajo a la factura', descripcion: 'Órdenes de trabajo en SIEGIX Provider', esVideo: false },
  { ruta: '/img/empresariales/siegix-provider/beneficios.webp', grupo: 'Soluciones empresariales', contexto: 'Control real de lo que pasa en la calle', descripcion: 'Supervisor revisando servicios en curso', esVideo: false },
  { ruta: '/img/empresariales/siegix-provider/industrias.webp', grupo: 'Soluciones empresariales', contexto: 'Pensado para empresas de servicios de cualquier sector', descripcion: 'Técnicos de distintas industrias en campo', esVideo: false },
  { ruta: '/img/empresariales/siegix-provider/faq.webp', grupo: 'Soluciones empresariales', contexto: 'Lo que más nos preguntan', descripcion: 'Asistente virtual de LINKDICOM resolviendo preguntas frecuentes', esVideo: false },
  { ruta: '/img/empresariales/siegix-core/panel.webp', grupo: 'Soluciones empresariales', contexto: 'El puente entre tu sistema y la Facturación Electrónica', descripcion: 'Panel de SIEGIX Core con el estado de los comprobantes en la DGII', esVideo: false },
  { ruta: '/img/empresariales/siegix-core/descripcion.webp', grupo: 'Soluciones empresariales', contexto: 'Conecta tu negocio con la DGII, sin complicaciones', descripcion: 'Esquema: tu sistema de facturación, SIEGIX Core y la DGII', esVideo: false },
  { ruta: '/img/empresariales/siegix-core/funcionalidades.webp', grupo: 'Soluciones empresariales', contexto: 'El proceso técnico, resuelto de principio a fin', descripcion: 'Panel de control de comprobantes electrónicos', esVideo: false },
  { ruta: '/img/empresariales/siegix-core/beneficios.webp', grupo: 'Soluciones empresariales', contexto: 'Cumples con la norma sin cambiar de software', descripcion: 'Responsable fiscal revisando comprobantes', esVideo: false },
  { ruta: '/img/empresariales/siegix-core/integraciones.webp', grupo: 'Soluciones empresariales', contexto: 'Se conecta como mejor le venga a tu sistema', descripcion: 'Diagrama de las formas de integración de SIEGIX Core', esVideo: false },
  { ruta: '/img/empresariales/siegix-core/faq.webp', grupo: 'Soluciones empresariales', contexto: 'Lo que más nos preguntan', descripcion: 'Asistente virtual de LINKDICOM resolviendo preguntas frecuentes', esVideo: false },
  { ruta: '/img/empresa/hero-acerca.webp', grupo: 'Empresa', contexto: 'Acerca de', descripcion: 'Especialista revisando estudios de imagen junto a la bandera dominicana', esVideo: false },
  { ruta: '/img/empresa/fundador-banderas.webp', grupo: 'Empresa', contexto: '', descripcion: 'Banderas de países de Latinoamérica ondeando frente a una ciudad al amanecer', esVideo: false },
  { ruta: '/img/empresa/cierre-acerca.webp', grupo: 'Empresa', contexto: 'Seguimos construyendo un futuro', descripcion: 'Ciudad al atardecer con el mapa de América conectado por una red de luz', esVideo: false },
  { ruta: '/img/empresa/hero-valores.webp', grupo: 'Empresa', contexto: 'Nuestros', descripcion: 'Edificio de LINKDICOM iluminado al anochecer', esVideo: false },
  { ruta: '/img/empresa/valor-compromiso.webp', grupo: 'Empresa', contexto: 'Compromiso', descripcion: 'Manos de un equipo unidas en señal de compromiso', esVideo: false },
  { ruta: '/img/empresa/valor-calidad.webp', grupo: 'Empresa', contexto: 'Calidad', descripcion: 'Comprobación de calidad sobre una interfaz digital', esVideo: false },
  { ruta: '/img/empresa/valor-social.webp', grupo: 'Empresa', contexto: 'Responsabilidad social', descripcion: 'Entrega de ayuda a una familia de la comunidad', esVideo: false },
  { ruta: '/img/empresa/valor-equipo.webp', grupo: 'Empresa', contexto: 'Trabajo en equipo', descripcion: 'Equipo de LINKDICOM trabajando junto a un portátil', esVideo: false },
  { ruta: '/img/empresa/valor-cliente.webp', grupo: 'Empresa', contexto: 'Orientación al cliente', descripcion: 'Especialista de soporte atendiendo con auriculares', esVideo: false },
  { ruta: '/img/empresa/cierre-valores.webp', grupo: 'Empresa', contexto: 'Únete a este', descripcion: 'Colaborador de LINKDICOM frente a su puesto de trabajo', esVideo: false },
  { ruta: '/img/empresa/hero-contacto.webp', grupo: 'Empresa', contexto: 'Contáct', descripcion: 'Sede de LINKDICOM iluminada al anochecer', esVideo: false },
  { ruta: '/img/empresa/cierre-contacto.webp', grupo: 'Empresa', contexto: 'Más que tecnología,', descripcion: 'Colaborador de LINKDICOM atendiendo desde la oficina', esVideo: false },
  { ruta: '/img/empresa/historia-hero.webp', grupo: 'Nuestra historia', contexto: 'Nuestra', descripcion: 'Bandera de la República Dominicana ondeando sobre la ciudad al atardecer', esVideo: false },
  { ruta: '/img/sectores/oviyam.webp', grupo: 'Nuestra historia', contexto: 'El comienzo de la colaboración internacional', descripcion: 'Apretón de manos entre LINKDICOM y una organización internacional', esVideo: false },
  { ruta: '/img/recursos/desarrollo.webp', grupo: 'Recursos', contexto: 'Materiales de Apoyo', descripcion: 'Especialista de LINKDICOM señalando los materiales de apoyo en pantalla', esVideo: false },
  { ruta: '/img/empresa/hero-politicas.webp', grupo: 'Políticas', contexto: 'Políticas y', descripcion: 'Recepción de las oficinas de LINKDICOM con el logotipo en la pared', esVideo: false },
  { ruta: '/img/empresa/cierre-politicas.webp', grupo: 'Políticas', contexto: 'Transparencia en cada', descripcion: 'Portátil mostrando un escudo de seguridad digital', esVideo: false },
  { ruta: '/img/empresa/hero-trabaja.webp', grupo: 'Trabaja con nosotros', contexto: 'Trabaja con', descripcion: 'Equipo de LINKDICOM trabajando junto en la oficina', esVideo: false },
  { ruta: '/img/empresa/cierre-trabaja.webp', grupo: 'Trabaja con nosotros', contexto: 'Aquí tu talento', descripcion: 'Sala de reuniones de LINKDICOM con el logotipo en la pared', esVideo: false },
  { ruta: '/img/empresa/hero-obra-social.webp', grupo: 'Obra social', contexto: 'Virginia', descripcion: 'Sede de LINKDICOM iluminada al anochecer', esVideo: false },
  { ruta: '/img/empresa/virginia.webp', grupo: 'Obra social', contexto: 'Virginia', descripcion: 'Retrato de la Sra. Virginia Alcántara Rivera', esVideo: false },
  { ruta: '/img/empresa/cierre-obra-social.webp', grupo: 'Obra social', contexto: 'Tu apoyo también', descripcion: 'Manos entregando una caja de donación de LINKDICOM', esVideo: false },
  { ruta: '/img/heros.png', grupo: 'Inicio y menú', contexto: 'Portada', descripcion: 'Ilustración de la portada del inicio', esVideo: false },
  { ruta: '/img/demo-enviando.webp', grupo: 'Formularios', contexto: 'Formulario de demo', descripcion: 'Ilustración del panel «Enviando tu solicitud»', esVideo: false },
  { ruta: '/img/obra-social/donacion-lado.webp', grupo: 'Obra social', contexto: 'Formulario de aporte', descripcion: 'Foto lateral del formulario «Quiero aportar»', esVideo: false },
  { ruta: '/video/intro-cables.mp4', grupo: 'Videos', contexto: 'Animación de entrada', descripcion: 'Video de la animación de entrada (cables que se conectan)', esVideo: true },
  { ruta: '/video/intro-poster.jpg', grupo: 'Videos', contexto: 'Animación de entrada', descripcion: 'Fotograma de espera de la animación de entrada', esVideo: false },
  { ruta: '/video/linkdicom-presentacion.mp4', grupo: 'Videos', contexto: 'Presentación', descripcion: 'Video de presentación de LINKDICOM (botón «Ver video»)', esVideo: true },
  { ruta: '/video/portada.jpg', grupo: 'Videos', contexto: 'Presentación', descripcion: 'Portada del video de presentación', esVideo: false },
];
